name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301    
    - name: Install dependencies
      working-directory: ./NugetPakcageTriage
      run: dotnet restore
    - name: Build
      working-directory: ./NugetPakcageTriage
      run: dotnet build --configuration Release --no-restore
    - name: Nuget triage
      working-directory: ./NugetPakcageTriage
      run: | 
        dotnet tool install -g NuSight
        nusight list -o -i -p -u
